const countryCodes = [
    { code: "+1", country: "États-Unis" },
    { code: "+33", country: "France" },
    { code: "+44", country: "Royaume-Uni" },
    { code: "+49", country: "Allemagne" },
    { code: "+55", country: "Brésil" },
    { code: "+91", country: "Inde" },
    { code: "+81", country: "Japon" },
    { code: "+61", country: "Australie" },
    { code: "+229", country: "Benin" },
    { code: "+1", country: "United States" },
    { code: "+44", country: "United Kingdom" },
    { code: "+33", country: "France" },
    { code: "+49", country: "Germany" },
    { code: "+91", country: "India" },
    { code: "+86", country: "China" },
    { code: "+81", country: "Japan" },
    { code: "+55", country: "Brazil" },
    { code: "+7", country: "Russia" },
    { code: "+61", country: "Australia" },
    { code: "+39", country: "Italy" },
    { code: "+34", country: "Spain" },
    { code: "+1", country: "Canada" },
    { code: "+27", country: "South Africa" },
    { code: "+31", country: "Netherlands" },
    { code: "+46", country: "Sweden" },
    { code: "+41", country: "Switzerland" },
    { code: "+32", country: "Belgium" },
    { code: "+52", country: "Mexico" },
    { code: "+82", country: "South Korea" },
    { code: "+420", country: "Czech Republic" },
    { code: "+48", country: "Poland" },
    { code: "+65", country: "Singapore" },
    { code: "+45", country: "Denmark" },
    { code: "+90", country: "Turkey" },
    { code: "+20", country: "Egypt" },
    { code: "+62", country: "Indonesia" },
    { code: "+66", country: "Thailand" },
    { code: "+64", country: "New Zealand" },
    { code: "+386", country: "Slovenia" },
    { code: "+354", country: "Iceland" },
    { code: "+374", country: "Armenia" },
    { code: "+98", country: "Iran" },
    { code: "+963", country: "Syria" },
    { code: "+961", country: "Lebanon" },
    { code: "+962", country: "Jordan" },
    { code: "+994", country: "Azerbaijan" },
    { code: "+975", country: "Bhutan" },
    { code: "+856", country: "Laos" },
    { code: "+855", country: "Cambodia" },
    { code: "+95", country: "Myanmar" },
    { code: "+84", country: "Vietnam" },
    { code: "+213", country: "Algeria" },
    { code: "+216", country: "Tunisia" },
    { code: "+212", country: "Morocco" },
    { code: "+251", country: "Ethiopia" },
    { code: "+254", country: "Kenya" },
    { code: "+256", country: "Uganda" },
    { code: "+234", country: "Nigeria" },
    { code: "+233", country: "Ghana" },
    { code: "+221", country: "Senegal" },
    { code: "+225", country: "Ivory Coast" },
    { code: "+237", country: "Cameroon" },
    { code: "+243", country: "Democratic Republic of the Congo" },
    { code: "+267", country: "Botswana" },
    { code: "+260", country: "Zambia" },
    { code: "+263", country: "Zimbabwe" },
    { code: "+56", country: "Chile" },
    { code: "+54", country: "Argentina" },
    { code: "+598", country: "Uruguay" },
    { code: "+591", country: "Bolivia" },
    { code: "+595", country: "Paraguay" },
    { code: "+57", country: "Colombia" },
    { code: "+503", country: "El Salvador" },
    { code: "+502", country: "Guatemala" },
    { code: "+505", country: "Nicaragua" },
    { code: "+507", country: "Panama" },
    { code: "+509", country: "Haiti" },
    { code: "+1473", country: "Grenada" },
    { code: "+1876", country: "Jamaica" },
    { code: "+1868", country: "Trinidad and Tobago" },
    { code: "+1242", country: "Bahamas" },
    { code: "+1264", country: "Anguilla" },
    { code: "+1268", country: "Antigua and Barbuda" },
    { code: "+1441", country: "Bermuda" },
    { code: "+1784", country: "Saint Vincent and the Grenadines" },
    { code: "+1869", country: "Saint Kitts and Nevis" },
    { code: "+1758", country: "Saint Lucia" },
    { code: "+967", country: "Yemen" },
    { code: "+974", country: "Qatar" },
    { code: "+968", country: "Oman" },
    { code: "+971", country: "United Arab Emirates" },
    { code: "+966", country: "Saudi Arabia" },
    { code: "+964", country: "Iraq" },
    { code: "+993", country: "Turkmenistan" },
    { code: "+992", country: "Tajikistan" },
    { code: "+996", country: "Kyrgyzstan" },
    { code: "+998", country: "Uzbekistan" },
    { code: "+373", country: "Moldova" },
    { code: "+382", country: "Montenegro" },
    { code: "+389", country: "North Macedonia" },
    { code: "+380", country: "Ukraine" },
    { code: "+375", country: "Belarus" },
    { code: "+372", country: "Estonia" },
    { code: "+358", country: "Finland" },
    { code: "+377", country: "Monaco" },
    { code: "+378", country: "San Marino" },
    { code: "+380", country: "Ukraine" },
    { code: "+356", country: "Malta" },
    { code: "+357", country: "Cyprus" },
    { code: "+379", country: "Vatican City" }
];


export default countryCodes